<h2 style="color:green" align="center">Machine Learning With Python: Save And Load Trained Model</h2>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [7]:
df.price

0    550000
1    565000
2    610000
3    680000
4    725000
Name: price, dtype: int64

In [3]:
type(df.price)

pandas.core.series.Series

In [4]:
df[['area']]

area
0  2600
1  3000
2  3200
3  3600
4  4000

In [11]:
type(df[['area']])

pandas.core.frame.DataFrame

In [5]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [6]:
model.coef_

array([135.78767123])

In [7]:
model.intercept_

180616.43835616432

In [8]:
model.predict([[5000]])

array([859554.79452055])

<h3 style='color:purple'>Save Model To a File Using Python Pickle</h3>

In [10]:
import pickle

In [11]:
with open('model_pickle_aug_2020','wb') as file:
    pickle.dump(model,file)

<h4 style='color:purple'>Load Saved Model</h4>

In [12]:
with open('model_pickle_aug_2020','rb') as file:
    mp = pickle.load(file)

In [13]:
mp.coef_

array([135.78767123])

In [14]:
mp.intercept_

180616.43835616432

In [15]:
mp.predict([[5000]])

array([859554.79452055])

<h3 style='color:purple'>Save Trained Model Using joblib</h3>

In [16]:
from sklearn.externals import joblib

C:\Users\lenovo\anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [17]:
joblib.dump(model, 'model_joblib_aug_2020')

['model_joblib_aug_2020']

<h4 style='color:purple'>Load Saved Model</h4>

In [18]:
mj = joblib.load('model_joblib')

C:\Users\lenovo\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.linear_model.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.linear_model. Anything that cannot be imported from sklearn.linear_model is now part of the private API.
  warnings.warn(message, FutureWarning)
C:\Users\lenovo\anaconda3\lib\site-packages\sklearn\base.py:318: UserWarning: Trying to unpickle estimator LinearRegression from version 0.21.3 when using version 0.22.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [19]:
mj.coef_

array([135.78767123])

In [20]:
mj.intercept_

180616.43835616432

In [21]:
mj.predict([[5000]])

array([859554.79452055])